---
exclude: |
  (?x)
  # You don't usually want a bot to modify your legal texts
  (LICENSE.*|COPYING.*)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=no]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [-x]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-lint
        name: lint TOML (taplo)
        # The online schema catalog currently fails to decode
        args: [--no-schema]
      - id: taplo-format
        name: format TOML (taplo)

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: lint YAML
        args: ["-d {rules: {line-length: disable}}", "-s"]

  - repo: local
    hooks:
      - id: kubeconform
        name: validate k8s manifests (kubeconform)
        entry: make validate
        language: system
        files: ^k8s/
        pass_filenames: false
