[options]
addons_path = /mnt/dynamist-addons
data_dir = /var/lib/odoo
; Development master password, overridden by the ODOO_ADMIN_PASSWD env var
admin_passwd = supersecr3tmasterpassw0rdfordevelop1
list_db = True
http_interface = 0.0.0.0
proxy_mode = False
workers = 0
max_cron_threads = 1
limit_time_real = 600
log_level = info
