apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # Shared CI runners are slower, give the first install more time
  - target:
      kind: Deployment
      name: odoo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/startupProbe/failureThreshold
        value: 360
